### ISSUE TITLE
Failed to Connect to LDAP Server from Openshift

### ISSUE THREAD

**Issue by sujith1594** [redhat-cop/group-sync-operator#172]
Hi Team,

We are trying to connect to LDAP Server from Openshift using Group Sync Operator.
We are getting the below error:
`
could not connect to the LDAP server: LDAP Result code 200 "Network Error": x509: certificate relies on legacy Common Name field, use SANs instead.
`

Can Someone help on this ?

Attaching the group sync yaml file
[groupsync.txt](https://github.com/redhat-cop/group-sync-operator/files/8225489/groupsync.txt)

Regards,
Sujith.

**Comment by sabre1041** [comment]
@sujith1594 The error that you receiving is due to the certificate that you are providing to the operator. golang requires that the hostname be present in the Subject Alternative Name field of the certificate.

By providing a certificate with this field present, you should be able to communicate with the LDAP server

**Comment by sabre1041** [comment]
@sujith1594 yes, it need to be added at certificate generation

**Comment by sujith1594** [comment]
@sabre1041 What is the hostname that I need to provide while certificate generation ?

**Comment by sabre1041** [comment]
The same hostname that is used in the `CN` can be used in the `SAN` field

**Comment by sabre1041** [comment]
Closing issue as stale
